# Service description for Anker Solix custom integration

get_system_info:
  target:
    entity:
      integration: anker_solix
      domain: sensor
      # anker_solix.AnkerSolixEntityFeature.SYSTEM_INFO is not resolved by HA core when frontend is loaded and does not work as filter
      # therefore a proper core domain feature is used as filter that resolves to same IntFlag as used in AnkerSolixEntityFeature
      supported_features:
        - calendar.CalendarEntityFeature.UPDATE_EVENT
  fields:
    include_cache:
      required: true
      example: true
      default: false
      selector:
        boolean:
export_systems:
  target:
    entity:
      integration: anker_solix
      domain: switch
      # anker_solix.AnkerSolixEntityFeature.ACCOUNT_INFO is not resolved by HA core when frontend is loaded and does not work as filter
      # therefore a proper core domain feature is used as filter that resolves to same IntFlag as used in AnkerSolixEntityFeature
      supported_features:
        - update.UpdateEntityFeature.SPECIFIC_VERSION
get_solarbank_schedule:
  target:
    entity:
      integration: anker_solix
      domain: sensor
      # anker_solix.AnkerSolixEntityFeature.SOLARBANK_SCHEDULE is not resolved by HA core when frontend is loaded and does not work as filter
      # therefore a proper core domain feature is used as filter that resolves to same IntFlag as used in AnkerSolixEntityFeature
      supported_features:
        - calendar.CalendarEntityFeature.CREATE_EVENT
clear_solarbank_schedule:
  target:
    entity:
      integration: anker_solix
      domain: sensor
      # anker_solix.AnkerSolixEntityFeature.SOLARBANK_SCHEDULE is not resolved by HA core when frontend is loaded and does not work as filter
      # therefore a proper core domain feature is used as filter that resolves to same IntFlag as used in AnkerSolixEntityFeature
      supported_features:
        - calendar.CalendarEntityFeature.CREATE_EVENT
  fields:
    sb2_fields:
      # Following section is used only for Solarbank 2 schedule types
      collapsed: true
      fields:
        plan:
          required: false
          example:
            - blend_plan
          selector:
            select:
              mode: list
              multiple: false
              translation_key: plan
              options:
                - custom_rate_plan
                - blend_plan
                - manual_backup
                - use_time
        week_days:
          required: false
          example:
            - sun
          selector:
            select:
              mode: list
              multiple: true
              translation_key: weekday
              options:
                - sun
                - mon
                - tue
                - wed
                - thu
                - fri
                - sat
set_solarbank_schedule:
  target:
    entity:
      integration: anker_solix
      domain: sensor
      # anker_solix.AnkerSolixEntityFeature.SOLARBANK_SCHEDULE is not resolved by HA core when frontend is loaded and does not work as filter
      # therefore a proper core domain feature is used as filter that resolves to same IntFlag as used in AnkerSolixEntityFeature
      supported_features:
        - calendar.CalendarEntityFeature.CREATE_EVENT
  fields:
    start_time:
      required: true
      example: "00:00:00"
      default: "00:00:00"
      selector:
        time:
    end_time:
      required: true
      example: "23:59:00"
      default: "23:59:00"
      selector:
        time:
    sb2_fields:
      # Following section is used only for Solarbank 2 schedule types
      collapsed: true
      fields:
        plan:
          required: false
          example:
            - blend_plan
          selector:
            select:
              mode: list
              multiple: false
              translation_key: plan
              options:
                - custom_rate_plan
                - blend_plan
        week_days:
          required: false
          example:
            - sun
          selector:
            select:
              mode: list
              multiple: true
              translation_key: weekday
              options:
                - sun
                - mon
                - tue
                - wed
                - thu
                - fri
                - sat
    appliance_load:
      required: false
      example: 100
      default: 100
      selector:
        number:
          min: 0
          max: 1600
          step: 10
          unit_of_measurement: "W"
    sb1_fields:
      # Following section is used only for Solarbank 1 schedule types
      collapsed: true
      fields:
        device_load:
          required: false
          example: 50
          selector:
            number:
              min: 50
              max: 800
              step: 5
              unit_of_measurement: "W"
        allow_export:
          required: false
          example: true
          selector:
            boolean:
        discharge_priority:
          required: false
          example: false
          selector:
            boolean:
        charge_priority_limit:
          required: false
          example: 80
          selector:
            number:
              min: 0
              max: 100
              step: 5
              unit_of_measurement: "%"
update_solarbank_schedule:
  target:
    entity:
      integration: anker_solix
      domain: sensor
      # anker_solix.AnkerSolixEntityFeature.SOLARBANK_SCHEDULE is not resolved by HA core when frontend is loaded and does not work as filter
      # therefore a proper core domain feature is used as filter that resolves to same IntFlag as used in AnkerSolixEntityFeature
      supported_features:
        - calendar.CalendarEntityFeature.CREATE_EVENT
  fields:
    start_time:
      required: true
      example: "00:00:00"
      default: "00:00:00"
      selector:
        time:
    end_time:
      required: true
      example: "23:59:00"
      default: "23:59:00"
      selector:
        time:
    sb2_fields:
      # Following section is used only for Solarbank 2 schedule types
      collapsed: true
      fields:
        plan:
          required: false
          example:
            - blend_plan
          selector:
            select:
              mode: list
              multiple: false
              translation_key: plan
              options:
                - custom_rate_plan
                - blend_plan
        week_days:
          required: false
          example:
            - sun
          selector:
            select:
              mode: list
              multiple: true
              translation_key: weekday
              options:
                - sun
                - mon
                - tue
                - wed
                - thu
                - fri
                - sat
    appliance_load:
      required: false
      example: 100
      default: 100
      selector:
        number:
          min: 0
          max: 1600
          step: 10
          unit_of_measurement: "W"
    sb1_fields:
      # Following section is used only for Solarbank 1 schedule types
      collapsed: true
      fields:
        device_load:
          required: false
          example: 50
          selector:
            number:
              min: 50
              max: 800
              step: 5
              unit_of_measurement: "W"
        allow_export:
          required: false
          example: true
          selector:
            boolean:
        discharge_priority:
          required: false
          example: false
          selector:
            boolean:
        charge_priority_limit:
          required: false
          example: 80
          selector:
            number:
              min: 0
              max: 100
              step: 5
              unit_of_measurement: "%"
